### ISSUE TITLE
Assessment 3

### ISSUE THREAD

**Issue by rizzamandasari** [Mielola/assesment3#1]
Aplikasi berjalan dnegan baik, tapi:
1. Input Pelaporan tugas tidak bisa. Tidak ada respon dan tidak ada feedback.
2. Ini aplikasi apa ko ada nama latin?

**Comment by Mielola** [comment]
Untuk masalah kedua, ini adalah aplikasi absen, Bu. Setelah saya cek, tidak ada nama latin yang muncul. Jika boleh tahu, nama latin yang dimaksud itu ada di bagian mana ya, Bu ?

Setelah saya cek kembali ternyata button untuk inputan menggunakan FAB saya disable saat user belum melakukan login sehingga feedback tidak bisa didapatkan saat ingin menginput tapi belum melakukan login. Untuk menginput absen memang agak lama bu.

Izin melampirkan Link Gdrive revisi aplikasi  ibu:
https://drive.google.com/drive/folders/1jxdb6Cn7XHj7BCQNXX_BblQSPJ1VLzd3?usp=sharing

Beberapa fitur yang saya revisi :
1. Memperbaiki logika FAB

**Comment by rizzamandasari** [comment]
OK. Close ketukare dengan punya Muhammad.
